---
title: "Network dynamics are associated with reinforcement learning"
author: "Raphael Gerraty"
subtitle: Figures
output: pdf_document
---


```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(sjPlot)
library(lme4)
library(brms)

stat_sum_single <- function(fun, geom="point",color="black", ...) {
  stat_summary(fun.y=fun, colour=color, geom=geom, size = 2, ...)
}

se<-function(x) (sd(x, na.rm=T)/sqrt(length(x)))
lose<-function(x) mean(x) - (sd(x, na.rm=T)/sqrt(length(x)))
hise<-function(x) mean(x) + (sd(x, na.rm=T)/sqrt(length(x)))

flex_behav<-read.csv('~/Downloads/flex_behav.csv')
mem_data<-read.csv('~/Downloads/mem_behav.csv')
rl_data<-read.csv('~/Documents/alphabeta.csv',header=0)

names(rl_data)<-c("alpha","beta")
```

##Figure 2a. 
```{r, echo=FALSE, warning=FALSE, message=FALSE}
#Learning
ggplot(flex_behav,aes(x=block,y=correct))+
  stat_sum_single(mean,geom="line")+
  stat_summary(fun.ymin=lose,fun.ymax=hise,geom="errorbar",
               position=position_dodge(.9),color = 'black', size=.5, width=0.2)  +
  theme_classic()+
  theme(legend.position="none",
        axis.title = element_text(size = 22),
        axis.text = element_text(size = 18))+
  xlab("Learning Block")+
  ylab("Proportion Correct")

```

##Figure 2c.
```{r echo=FALSE, warning=FALSE, message=FALSE}
##Plote flexibility over time
#whole-brain
p<-ggplot(data=flex_behav,aes(block,wb_flex))

p+geom_line(aes(color=as.factor(subject)),alpha=.9)+
  stat_sum_single(mean,geom="line")+
  theme_classic()+
  theme(legend.position="none",
        axis.title = element_text(size = 22),
        axis.text = element_text(size = 18))+
  xlab("Learning Block")+
  ylab("Whole-Brain Flexibility")


```

##Figure 3a
```{r echo=FALSE, warning=FALSE, message=FALSE}
mlearn_glmer<-glmer(correct~str_flex_dm+(str_flex_dm||subject),data=flex_behav,family=binomial("logit"),weights=weights)

#because sjplot doesn't like proportions?
flex_behav_big<-read.csv('~/Downloads/flex_behav_big.csv')
flex_behav_big<-flex_behav_big[!is.na(flex_behav_big$correct),]

mlearn_glmer_big<-glmer(correct~str_flex+(str_flex||subject),data=flex_behav_big,family=binomial("logit"))
######

predict.data <- data.frame(flex_behav_big, response.logit = predict(mlearn_glmer_big, re.form=~(str_flex|subject),newdata=flex_behav_big), 
	fixed.logit = predict(mlearn_glmer_big, re.form=NA, newdata=flex_behav_big))
predict.data$response = 1/(1+exp(-predict.data$response.logit))
predict.data$fixed=1/(1+exp(-predict.data$fixed.logit))

####plot FE plus CI using sjPlot
a<-sjp.glmer(mlearn_glmer_big,type="fe.pc",show.ci=1,printPlot = FALSE)
gplot<-a$plot.mp[[1]]+theme_classic()+theme(legend.position="none")+
#ggtitle("Effect of Flexibility on Learning")+
ylab("Proportion Correct")+
xlab("Striatum Flexibility")+coord_cartesian(ylim = c(0.3, 1))+
theme(axis.title=element_text(size=22))

#add random effects lines (plus increase FE line)
gplot+geom_line(aes(x=predict.data$str_flex, y=predict.data$response,group=flex_behav_big$subject,colour=as.factor(flex_behav_big$subject)), alpha = .9,size=1)+
geom_line(aes(x=predict.data$str_flex, y=predict.data$fixed, group=1), color='black', size=1.25)+
theme(axis.title=element_text(size=22))+theme(axis.text=element_text(size=18))


```


##Figure 4
```{r echo=FALSE, warning=FALSE, message=FALSE}
###Reinforcement learning parameter flexibility correlation
rl_flex<-as.data.frame(cbind(tapply(flex_behav$wb_flex,flex_behav$subject,mean),                        tapply(flex_behav$str_flex,flex_behav$subject,mean),rl_data$alpha))
names(rl_flex)<-c("wb_flex","str_flex","alpha")

ggplot(data=rl_flex,aes(x=wb_flex,y=alpha))+theme_classic()+geom_point()+
  ylab("Learning Rate")+
  xlab("Whole-Brain Flexibility")+
  theme(axis.title=element_text(size=22))+
  theme(legend.position="none",
        axis.text = element_text(size = 18))+
  stat_smooth(method=lm)

```


##Figure 5a
```{r echo=FALSE, warning=FALSE, message=FALSE}
ggplot(mem_data,aes(x=block,y=correct))+
  stat_sum_single(mean,geom="line")+
  stat_summary(fun.ymin=lose,fun.ymax=hise,geom="errorbar",
               position=position_dodge(.9),color = 'black', size=.5, width=0.2)  +
  theme_classic()+
  theme(legend.position="none",
        axis.title = element_text(size = 22),
        axis.text = element_text(size = 18))+
  xlab("Learning Block")+
  ylab("Proportion Remembered")

```


##Supplementary Figures
```{r echo=FALSE, warning=FALSE, message=FALSE}
#striatum
p2<-ggplot(data=flex_behav,aes(block,str_flex))
p2+geom_line(aes(color=as.factor(subject)),alpha=.9)+
  stat_sum_single(mean,geom="line")+
  theme_classic()+
  theme(legend.position="none",
        axis.title = element_text(size = 22),
        axis.text = element_text(size = 18))+
  xlab("Learning Block")+
  ylab("Striatal Flexibility")

```

```{r echo=FALSE, warning=FALSE, message=FALSE}
##Whole-brain Flexibility and Learning#################################

#because sjplot doesn't like proportions?
mlearn_glmer_big_wb<-glmer(correct~wb_flex+(wb_flex||subject),data=flex_behav_big,family=binomial("logit"))
######

predict.data2 <- data.frame(flex_behav_big, response.logit = predict(mlearn_glmer_big_wb, re.form=~(wb_flex|subject),newdata=flex_behav_big), 
                           fixed.logit = predict(mlearn_glmer_big_wb, re.form=NA, newdata=flex_behav_big))
predict.data2$response = 1/(1+exp(-predict.data2$response.logit))
predict.data2$fixed=1/(1+exp(-predict.data2$fixed.logit))

####plot FE plus CI using sjPlot
a2<-sjp.glmer(mlearn_glmer_big_wb,type="fe.pc",show.ci=1,printPlot = FALSE)
gplot2<-a2$plot.mp[[1]]+theme_classic()+theme(legend.position="none")+
  #ggtitle("Effect of Flexibility on Learning")+
  ylab("Proportion Correct")+
  xlab("Whole-Brain Flexibility")+coord_cartesian(ylim = c(0.3, 1))+
  theme(axis.title=element_text(size=22))

#add random effects lines (plus increase FE line)
gplot2+geom_line(aes(x=predict.data2$wb_flex, y=predict.data2$response,group=flex_behav_big$subject,colour=as.factor(flex_behav_big$subject)), alpha = .9,size=1)+
  geom_line(aes(x=predict.data2$wb_flex, y=predict.data2$fixed, group=1), color='black', size=1.25)+
  theme(axis.title=element_text(size=22))+theme(axis.text=element_text(size=18))



```


```{r echo=FALSE, warning=FALSE, message=FALSE}
ggplot(data=rl_flex,aes(x=str_flex,y=alpha))+theme_classic()+geom_point()+
  ylab("Learning Rate")+
  xlab("Striatal Flexibility")+
  theme(axis.title=element_text(size=22))+
  theme(legend.position="none",
        axis.text = element_text(size = 18))+
  stat_smooth(method=lm)
```




